services:
  # Backend Service
  - type: web
    name: planthetrips-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
        required: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /api
    autoDeploy: true

  # Frontend Service
  - type: web
    name: planthetrips-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://planthetrips-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true 